Repository amaralc/hiPeer, pull requests merged in 2020-01, with the labels that each got.

#2 firmware: acionamento dos LEDs de todos os containers apernando um botao
  src/firmware/main/main.ino
  src/firmware/main/schematics.PNG
Labels: enhancement

#3 Infraestrutura - Configuração inicial de Docker
  .gitignore
  docker/.env
  docker/docker-compose.yml
  sql/.gitkeep
  sql/create-database.sql
  sql/create-users.sql
Labels: infrastructure

#5 feature/activate-containers-individually
  src/firmware/main/20200115_0553_firmware_each_container_individually_code_only.PNG
  src/firmware/main/20200115_0553_firmware_each_container_individually_code_only.fzz
  src/firmware/main/main.ino
  src/firmware/main/schematics.PNG
Labels: firmware

#8 FIRMWARE / FEATURE / Adiciona keypad input
  .vscode/arduino.json
  .vscode/c_cpp_properties.json
  src/firmware/doc/00-prototipo-com-arduino-mega.md
  src/firmware/doc/20200115_0553_firmware_each_container_individually_code_only.PNG
  src/firmware/doc/20200115_0553_firmware_each_container_individually_code_only.fzz
  src/firmware/main/main.ino
Labels: firmware

#11 Add keypad as input method
  .vscode/arduino.json
  .vscode/c_cpp_properties.json
  src/firmware/doc/00-prototipo-com-arduino-mega.md
  src/firmware/doc/20200115_0553_firmware_each_container_individually_code_only.PNG
  src/firmware/doc/20200115_0553_firmware_each_container_individually_code_only.fzz
  src/firmware/main/main.ino
Labels: firmware

#16 Insere feature de leitura do RFID e retira leitura de push button
  src/firmware/doc/00-prototipo-com-arduino-mega.md
  src/firmware/doc/schematics.PNG
  src/firmware/doc/schematics.fzz
  src/firmware/main/main.ino
Labels: firmware

#17 Cria migration de usuario
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/package.json
  src/api_client/src/config/database.js
  src/api_client/src/database/migrations/20200121143926-create-users.js
  src/api_client/yarn.lock
Labels: enhancement

#18 Cria model de usuario
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/src/app/models/User.js
Labels: feature

#19 Cria loader de models
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/src/app.js
  src/api_client/src/app/models/User.js
  src/api_client/src/config/database.js
  src/api_client/src/database/index.js
  src/api_client/src/database/migrations/20200121143926-create-users.js
  src/api_client/src/routes.js
  src/api_client/src/server.js
Labels: feature

#20 API-CLIENT / FEATURE / Cria migration de usuario, model de usuario e loader de models
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/package.json
  src/api_client/src/app.js
  src/api_client/src/app/models/User.js
  src/api_client/src/config/database.js
  src/api_client/src/database/index.js
  src/api_client/src/database/migrations/20200121143926-create-users.js
  src/api_client/src/routes.js
  src/api_client/src/server.js
  src/api_client/yarn.lock
Labels: feature

#21 Cria feature de cadastro de usuarios
  src/api_client/.eslintrc.js
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/src/app/controllers/UserController.js
  src/api_client/src/routes.js
Labels: feature

#22 Cria hash da senha
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/package.json
  src/api_client/src/app/models/User.js
  src/api_client/yarn.lock
Labels: feature

#23 API-CLIENT / DOCUMENTATION / 12 Conceitos de JWT
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
Labels: documentation

#24 Cria autenticacao JWT
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/doc/img/02-13-autenticacao-jwt-request.PNG
  src/api_client/doc/img/02-13-autenticacao-jwt-response.PNG
  src/api_client/package.json
  src/api_client/src/app/controllers/SessionController.js
  src/api_client/src/app/models/User.js
  src/api_client/src/config/auth.js
  src/api_client/src/routes.js
  src/api_client/yarn.lock
Labels: feature

#25 Cria middleware de autenticacao
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/src/app/controllers/.gitkeep
  src/api_client/src/app/controllers/UserController.js
  src/api_client/src/app/middlewares/auth.js
  src/api_client/src/routes.js
  src/api_client/template.js
Labels: feature

#26 Permite update de dados do usuario
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/src/app/controllers/UserController.js
Labels: feature

#27 Validacao de dados na entrada (backend)
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/package.json
  src/api_client/src/app/controllers/SessionController.js
  src/api_client/src/app/controllers/UserController.js
  src/api_client/yarn.lock
Labels: feature

#28 Adiciona primeira parte do backend do API-CLIENT ao branch dev
  src/api_client/.eslintrc.js
  src/api_client/doc/02-iniciando-back-end-do-gobarber.md
  src/api_client/doc/img/02-12-conceitos-de-jwt.PNG
  src/api_client/doc/img/02-13-autenticacao-jwt-request.PNG
  src/api_client/doc/img/02-13-autenticacao-jwt-response.PNG
  src/api_client/doc/img/02-14-bearer-token-on-auth.PNG
  src/api_client/doc/img/02-14-bearer-token-on-header.PNG
  src/api_client/package.json
  src/api_client/src/app/controllers/.gitkeep
  src/api_client/src/app/controllers/SessionController.js
  src/api_client/src/app/controllers/UserController.js
  src/api_client/src/app/middlewares/auth.js
  src/api_client/src/app/models/User.js
  src/api_client/src/config/auth.js
  src/api_client/src/routes.js
  src/api_client/template.js
  src/api_client/yarn.lock
Labels: feature

#29 Substituicao do monitor serial por display OLED para interacao com usuario
  src/firmware/doc/00-prototipo-com-arduino-mega.md
  src/firmware/doc/schematics.fzz
  src/firmware/main/main.ino
Labels: feature

#30 Add firmware functionalities to 'dev' branch
  src/firmware/doc/00-prototipo-com-arduino-mega.md
  src/firmware/doc/schematics.fzz
  src/firmware/main/main.ino
Labels: feature
